openapi: 3.0.2
info:
  title: SafeDep Control Plane API
  contact:
    name: SafeDep API
    url: 'https://safedep.io'
  description: |
    The SafeDep Control Plane API provides configuration and management plane
    access to clients for the SafeDep platform
  version: 0.0.1
servers:
  - url: 'https://{apiHost}/{apiBase}'
    variables:
      apiHost:
        default: api.safedep.io
      apiBase:
        default: control-plane/v1
tags:
  - name: Control Plane
    description: Control Plane API
paths:
  /auths/me:
    get:
      description: |
        Introspection API for getting configuration information associated
        with the supplied API credentials
      operationId: getApiCredentialIntrospection
      tags:
        - Control Plane
      responses:
        '200':
          description: API credentials introspection information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CredentialIntrospectionResponse'
        '403':
          description: Access to the API is denied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '429':
          description: Rate limit block
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Failed due to internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: Authorization
      in: header
  schemas:
    ApiError:
      type: object
      properties:
        message:
          type: string
          description: A descriptive message about the error meant for developer consumption
        type:
          type: string
          description: An optional service or domain specific error group
          enum:
            - invalid_request
            - operation_failed
            - internal_error
        code:
          type: string
          description: An error code identifying the error
          enum:
            - api_guard_invalid_credentials
            - api_guard_rate_limit_exceeded
            - api_guard_unauthorized
            - api_guard_error
            - app_generic_error
            - app_security_error
            - app_insufficient_parameters
            - app_feature_not_enabled
            - app_package_version_not_found
        params:
          type: object
          description: Optional error specific attributes
          additionalProperties:
            type: object
            properties:
              key:
                type: string
              value:
                type: string
    CredentialIntrospectionResponse:
      type: object
      properties:
        type:
          type: string
          description: The entity type to which this credential belongs to
          enum:
            - TrialUser
            - Organization
            - Team
            - User
        expiry:
          type: string
          description: Expiry timestamp in RFC3399 format if expirable
      required:
        - type
