name: CI
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
        with:
          go-version: 1.21
          check-latest: true

      - name: Build and Test
        run: |
          go mod tidy
          go build
          go test -v ./...
        env:
          VET_E2E: true

  build-container:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Container Image
      run: |
        docker buildx build --platform linux/amd64 --platform linux/arm64 \
        -t build-container-test .

