name: vet OSS Components

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write
  pull-requests: write
  security-events: write

jobs:
  vet:
    name: vet
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Run vet
        uses: safedep/vet-action@v1
        with:
          policy: .github/vet/policy.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
